### ISSUE TITLE
Move Catalog details to its own spec

### ISSUE THREAD

**Issue by suhasHere** [kixelated/warp-draft#85] opened 2023-02-01 00:30 UTC
Today the protocol specifies the format of the catalog message. Should we keep it opaque and have an extension spec to define container specific catalog formats

**Comment by vasilvv** [comment] 2023-02-01 19:41
If we remove CATALOG, how would we deal with INIT segments?

**Comment by kixelated** [comment] 2023-02-01 22:11
INIT segments could be in the catalog itself, kind of like how you can base64 them in DASH.

**Comment by afrind** [comment] 2023-02-03 01:17
Is this a duplicate of #66?

**Comment by suhasHere** [comment] 2023-02-13 01:29
Agree with @kixelated .. If the container type is CMAF, the init segment is part of Catalog for a given track. This issue is proposing moving format specific catalog definition to companion spec IIUC from the discussions

**Comment by afrind** [comment] 2023-04-21 19:30
Is this a duplicate of #66

**Closed** 2023-05-05 19:50 UTC
Labels: interim-jan
