### ISSUE TITLE
Move the streaming format description outside the base spec

### ISSUE THREAD

**Issue by suhasHere** [kixelated/warp-draft#113] opened 2023-03-30 08:06 UTC
This is reflecting the discussions on having a separate spec describe the streaming format (cmaf, webcodecs based format)

**Comment by fluffy** [comment] 2023-04-07 20:26
+1 on doing this.

**Comment by kixelated** [comment] 2023-04-10 17:55
I'm going to work on splitting the warp draft into a transport only section. Will started the media half here: https://github.com/wilaw/MoQ

I want these to be in the same GitHub repo eventually. Should we do that now or wait for adoption?

**Comment by afrind** [comment] 2023-04-21 19:28
See also #66, maybe one of these can be closed as a duplicate?

**Comment by afrind** [comment] 2023-05-05 19:52
Duplicate of #66 and related to #146

**Closed by afrind** 2023-05-05 19:52 UTC
