### ISSUE TITLE
Add support for specifying start point for Subscription

### ISSUE THREAD

**Issue by suhasHere** [kixelated/warp-draft#133] opened 2023-04-10 16:26 UTC
Allowing a way to specify the start point ( right group number and object number) will allow subscriptions to support use-case such as
- Catch up from the right place in the track
- Replay from a specific point in the track

This will be a follow up to #122

**Comment by kixelated** [comment] 2023-04-10 17:35
Thanks for listing some use-cases. I agree that an optional group ID would be good in the SUBSCRIBE message.

I'm not sure that including an object ID is necessary though. It miiight be useful if a connection is severed half-way through a group, but that seems very fringe. Are there other use-cases or can we punt it for now?

**Comment by kixelated** [comment] 2023-04-10 19:51
duplicate of #111

**Comment by afrind** [comment] 2023-05-05 20:06
SUBSCRIBE REQUEST has parameters that allow the receiver to specify the start point.

**Closed by afrind** 2023-05-05 20:06 UTC
