### ISSUE TITLE
MoQ Control Stream Support for managing the data streams

### ISSUE THREAD

**Issue by suhasHere** [kixelated/warp-draft#81] opened 2023-01-31 17:51 UTC

**Comment by kixelated** [comment] 2023-01-31 18:15
I can imagine a relay would want to push multiple broadcasts over a single QUIC connection. A single control stream would introduce head-of-line blocking.

A few options:

1. Don't care about HoL blocking
2. Create a WebTransport session per broadcast
3. Create a control stream per broadcast

I personally like the 3rd option.

**Comment by kixelated** [comment] 2023-01-31 18:19
To clarify, the current draft doesn't specify how you're supposed to use streams outside of SETUP.

Personally, I like something similar to HTTP/3, which would let an implementation do any of the three options.

Each control stream would start with a SETUP message (like H3 SETTINGS). Any messages for a broadcast (CATALOG/SUBSCRIBE) must use the same control stream. The publisher can create any number of data streams to send OBJECTs.

**Comment by afrind** [comment] 2023-04-21 19:33
Possible duplicate now with #138 -- can we merge them?

**Comment by afrind** [comment] 2023-05-05 19:50
Duplicate of #138

**Closed by afrind** 2023-05-05 19:50 UTC
Labels: Requirement
