### ISSUE TITLE
Add text to talk about Relays and Pub/Sub

### ISSUE THREAD

**Issue by suhasHere** [kixelated/warp-draft#54] opened 2022-11-23 04:51 UTC
The draft should specify more information on aspects of Relays such as their role in forwarding/caching, interactions with pub/sub flow and the data model to meet the charter goals (https://datatracker.ietf.org/wg/moq/about/)

**Comment by suhasHere** [comment] 2022-11-23 04:52
I am in the middle of edits and part of my edits is fate shared with messages PR as it needs to talk about pub/sub and how it interacts with Relays

**Comment by afrind** [comment] 2023-04-21 19:37
Is this a duplicate of #112 now - can merge them?

**Comment by afrind** [comment] 2023-05-05 19:49
Duplicate of #112

**Closed by afrind** 2023-05-05 19:49 UTC
Labels: Architectural
